---
name:                symspell
version:             0.1.0.0
synopsis:            SymSpell spelling correction
description:         Efficient spellchecking through symmetric delete pre-computation
category:            Language
github:              cbeav/symspell
license:             BSD3
author:              Chris Beavers
maintainer:          Chris Beavers <crbeavers@gmail.com>
homepage:            http://github.com/cbeav/symspell

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- aeson
- aeson-casing
- attoparsec
- base >= 4.7 && < 5
- classy-prelude
- closed
- containers
- data-default
- ghc-compact
- text
- text-metrics
- unordered-containers

library:
  source-dirs: src

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- DeriveGeneric
- ScopedTypeVariables
- TupleSections

executables:
  symspell-server:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant
    - servant-server
    - symspell
    - wai
    - warp

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - symspell
